language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
scripts:
  - test: nyc npm test && nyc report --reporter=text-lcov | coveralls
cache:
  directories:
    - node_modules
after_script:
  - npm run coverage
